# Generated by Django 4.2.7 on 2025-11-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='text_german',
            field=models.TextField(blank=True),
        ),
    ]
